"""teacher fullname unique=True

Revision ID: 07f98041587e
Revises: edde3de1672b
Create Date: 2024-07-30 00:05:11.718107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f98041587e'
down_revision: Union[str, None] = 'edde3de1672b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_name_key', 'teachers', type_='unique')
    op.create_unique_constraint('teachers_fullname_key', 'teachers', ['fullname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_fullname_key', 'teachers', type_='unique')
    op.create_unique_constraint('teachers_name_key', 'teachers', ['name'])
    # ### end Alembic commands ###
