"""date = Column(Date, nullable=False)

Revision ID: 35c66408248f
Revises: 74f5ca1067f6
Create Date: 2024-07-28 10:35:48.131389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35c66408248f'
down_revision: Union[str, None] = '74f5ca1067f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('marks', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('groups', 'number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
