"""groups.name -> groups.number

Revision ID: 404e8af4ba94
Revises: 7024d130f39a
Create Date: 2024-07-27 12:25:55.495112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404e8af4ba94'
down_revision: Union[str, None] = '7024d130f39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('number', sa.String(length=30), nullable=True))
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('groups', 'number')
    # ### end Alembic commands ###
