"""added marks f-keys

Revision ID: c8042e592b72
Revises: d1b075214fa8
Create Date: 2024-07-27 11:02:43.195706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8042e592b72'
down_revision: Union[str, None] = 'd1b075214fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('marks', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'marks', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint('subjects_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subjects_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_teacher_id_fkey', 'subjects', 'groups', ['teacher_id'], ['id'])
    op.drop_constraint('marks_student_id_fkey', 'marks', type_='foreignkey')
    op.drop_constraint('marks_subject_id_fkey', 'marks', type_='foreignkey')
    op.drop_column('marks', 'subject_id')
    op.drop_column('marks', 'student_id')
    # ### end Alembic commands ###
